### ISSUE TITLE
matrix_k_min function

### ISSUE THREAD

**Issue by antoalli** [Gorilla-Lab-SCUT/GPNet#3]
Hi! I was wondering what is actually doing the 'matrix_k_min' function, for example here https://github.com/CZ-Wu/GPNet/blob/59419f4505ca0732316a7d993bfe065547892847/tools/proposal.py#L396. What is actual being performed in the 389-398' for loop and what 'matrix_k_min' is accomplishing?

Thank you very much

**Comment by CZ-Wu** [comment]
It looks for the top k minimum values along each row of the matrix and return the indices. The loop there is to avoid out of memory. This function is for calculating the fixed size of neighbors of the contacts.

**Comment by CZ-Wu** [comment]
It looks for the top k minimum values along each row of the matrix and return the indices. The loop there is to avoid out of memory. This function is for calculating the fixed size of neighbors of the contacts.
