### ISSUE TITLE
offset in dataset

### ISSUE THREAD

**Issue by mrudorfer** [Gorilla-Lab-SCUT/GPNet#4]
Hello,

Thank you for providing a script to remove the offset of 0.015 in each grasp's z-direction from the contact points in the dataset.
However, this issue also seems to apply to the grasp centers - which are not yet corrected by the script.

Furthermore, when using the corrected data to train the network, we will presumably have to introduce this offset in the predictions to evaluate them in simulation. Is that correct?

Thanks in advance,
Martin

**Comment by matafela** [comment]
sorry for late reply. Yes, that's correct.
